title: GitHook Slack
description: Post messages to Slack on given webhook events.
thumbnail: https://cloud.githubusercontent.com/assets/5111927/19020896/f971cdfe-88ac-11e6-902e-faf73c4c08ad.jpg

entry_point: slack.js

triggered_on:
  - '*'

parameters:
  event:
    title: Event
    description: In response this this event...
    options:
      - PR opened
      - PR closed
      - PR reopened
      - PR edited
      - PR assigned
      - Issue opened
      - Issue closed
      - Issue reopened
      - Issue edited
      - Issue assigned
      - PR/Issue comment
      - Fork
      - Tag
    required: true
  text:
    title: Text
    description: Send this message...
    type: string
  channel:
    title: 'Channel (default: #general)'
    description: "#random, #general, #myprivatechannel, @username"
    type: string
  username:
    title: Username
    description: Username to post as. (Defaults to GitHooksIO)
    type: string
  emoji:
    title: Emoji
    description: Emoji to accompany the username (e.g. `:rocket`)
    type: string
  url:
    title: Slack Integration URL
    description: Will look something like https://hooks.slack.com/services/X/Y/Z
    type: url
    required: true
